#### **1. Introduction to NumPy**

#### **Task 1**: Import the NumPy library and print its version.

In [5]:
# Write your answer from this cell onwards
import numpy as np
np.__version__

'2.4.2'

**Task 2**: Create a one-dimensional NumPy array of integers from 0 to 9 and print it.

In [6]:
# Write your answer from this cell onwards
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


**Task 3**: Generate a two-dimensional NumPy array with random values and print its shape and data type.

In [7]:
# Write your answer from this cell onwards
arr2 = np.random.rand(3,3)
print(arr2)
print(arr2.shape)
print(arr2.dtype)

[[0.54326106 0.06625669 0.92106473]
 [0.93621902 0.56113291 0.25060646]
 [0.26358721 0.72405768 0.80511171]]
(3, 3)
float64


**Task 4**: Create a NumPy array with 50 evenly spaced values between 0 and 10.

In [8]:
# Write your answer from this cell onwards
a = np.linspace(0,10,50)
print(a)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


**Task 5**: Write a program to demonstrate the difference between a Python list and a NumPy array by performing element-wise addition on both.

In [9]:
# Write your answer from this cell onwards
a2 = np.random.rand(3,3)
arr2 = np.random.rand(3,3)
print(f"Addition of NumPy array: {a2+arr2}")

l = []
l1 = [1, 2, 3, 4]
l2 = [5, 6, 7, 8]
for i in range(len(l1)):
  sum = l1[i] + l2[i]
  l.append(sum)
print(f"Adition of list: {l}")

Addition of NumPy array: [[1.03955802 0.22570549 0.85805842]
 [1.0572329  0.23346391 0.77753759]
 [0.16394816 1.31381038 1.04399284]]
Adition of list: [6, 8, 10, 12]


---

#### **2. Creation of NumPy Arrays**

**Task 6**: Create a NumPy array of all zeros with a shape of (3, 4).

In [10]:
# Write your answer from this cell onwards
a3 = np.zeros((3,4))
print(a3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**Task 7**: Create a NumPy array of all ones with a shape of (2, 5) and a data type of float.

In [11]:
# Write your answer from this cell onwards
a4 = np.ones((2,5), dtype=float)
print(a4)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


**Task 8**: Use `arange()` to create a NumPy array containing numbers from 10 to 50 with a step of 5.

In [12]:
# Write your answer from this cell onwards
a5 = np.arange(10,50+1,5)
print(a5)

[10 15 20 25 30 35 40 45 50]


**Task 9**: Generate a 3x3 identity matrix using NumPy.

In [13]:
# Write your answer from this cell onwards
a6 = np.eye(3,3)
print(a6)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Task 10**: Create a 4x4 array filled with random integers between 1 and 20.

In [14]:
# Write your answer from this cell onwards
a7 = np.random.randint(1, 20, (4,4))
print(a7)

[[ 6  7  6 10]
 [17  8 16  4]
 [ 6  3  9  7]
 [15  2  4 15]]


---

#### **3. Indexing and Slicing of NumPy Arrays**

**Task 11**: Create a 1D NumPy array with values ranging from 1 to 15. Slice the array to extract elements from index 3 to 8.

In [15]:
# Write your answer from this cell onwards
a8 = np.arange(1,16)
print(f"Array: {a8}")
print(f"Slicing: {a8[3:9]}")

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Slicing: [4 5 6 7 8 9]


**Task 12**: Generate a 3x3 matrix with values ranging from 1 to 9. Retrieve the element at the second row and third column.

In [16]:
# Write your answer from this cell onwards
a9 = np.arange(1, 10).reshape(3,3)
print(f"Array: {a9}")
print(f"Element at the second row and third column: {a9[1,2]}")

Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at the second row and third column: 6


**Task 13**: Slice a 4x4 array to extract the last two rows and the last two columns.

In [17]:
# Write your answer from this cell onwards
a10 = np.random.randint(1, 20, (4,4))
print(f"Array: {a10}")
print(f"last two rows and the last two columns: {a10[2:,2:]}")

Array: [[ 3 15  7 15]
 [16 15 16  5]
 [ 2  2 11  4]
 [ 7 13 10  2]]
last two rows and the last two columns: [[11  4]
 [10  2]]


**Task 14**: Create a 5x5 matrix of random integers between 10 and 50. Replace all elements in the first row with the value 100.

In [18]:
# Write your answer from this cell onwards
a11 = np.random.randint(10, 50, (5,5))
print(f"Array: {a11}")
a11[0] = 100
print(f"Replaced array: {a11}")



Array: [[39 30 37 33 34]
 [37 20 14 20 12]
 [41 44 47 24 41]
 [34 23 32 40 14]
 [17 13 38 16 17]]
Replaced array: [[100 100 100 100 100]
 [ 37  20  14  20  12]
 [ 41  44  47  24  41]
 [ 34  23  32  40  14]
 [ 17  13  38  16  17]]


**Task 15**: Create a 1D NumPy array of 10 elements. Use boolean indexing to filter out all values greater than 5.

In [19]:
# Write your answer from this cell onwards
a12 = np.arange(1, 11)
print(f"Array: {a12}")
new = a12[a12 > 5]
print(f"Filtered array: {new}")

Array: [ 1  2  3  4  5  6  7  8  9 10]
Filtered array: [ 6  7  8  9 10]
